project:
  type: website
  pre-render:
    - julia --project make.jl

website:
  title: "Atlantis Subsidence (Atlans)"
  page-navigation: true
  navbar:
    left:
      - text: "Atlantis"
        file: core/index.qmd
      - text: "Input Data"
        file: data/index.qmd
      - text: "Usage"
        file: usage/index.qmd
      - text: "API reference"
        file: build/index.md
  
  sidebar:
    - title: "Atlantis"
      contents:
        - core/index.qmd
        - core/consolidation.qmd
        - core/oxidation.qmd
        - core/shrinkage.qmd
    - title: "Input Data"
      contents:
        - data/index.qmd
        - data/requirements.qmd
    - title: "Usage"
      contents:
        - usage/index.qmd
        - usage/build_model.ipynb
        - usage/build_column.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib

crossref: 
  fig-title: Fig.
  fig-prefix: Fig.
  title-delim: "."
